Repository codestates-seb/seb43_main_026, pull requests merged in 2023-05, with the labels that each got.

#14 Fe/header
  .DS_Store
  client/README.md
  client/src/App.js
  client/src/assets/images/로고.png
  client/src/index.js
  client/src/layout/Header.jsx
  client/src/style/theme.js
Labels: 🎨HTML&CSS

#15 Fe/nav 네브 컴포넌트 구현
  client/.eslintrc.json
  client/src/App.js
  client/src/index.js
  client/src/layout/Footer.jsx
  client/src/layout/Header.jsx
  client/src/layout/Nav.jsx
  client/src/style/GlobalStyle.js
  client/src/style/theme.js
Labels: 🎨HTML&CSS

#26 feat:Header의 아이콘에 Nav연결
  client/src/App.js
  client/src/layout/Header.jsx
  client/src/layout/Nav.jsx
Labels: 🔥Feature, 🎨HTML&CSS

#29 design: 레이아웃 전체적인 수정
  client/src/App.js
  client/src/component/common/Button.jsx
  client/src/component/common/ImageUpload.jsx
  client/src/layout/Footer.jsx
  client/src/layout/Header.jsx
  client/src/layout/Nav.jsx
  client/src/pages/Calendar.jsx
  client/src/style/theme.js
Labels: 🎨HTML&CSS

#30 Design : 글로벌 스타일 수정
  client/src/App.js
  client/src/layout/Header.jsx
  client/src/layout/Nav.jsx
  client/src/pages/Board.jsx
  client/src/style/GlobalStyle.js
  client/src/style/theme.js
Labels: 🎨HTML&CSS

#31 feat: 회원가입 구현중
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/pages/SignUp.jsx
  client/src/style/theme.js
Labels: 🔥Feature

#34 design:캘린더 메인 페이지 레이아웃(모바일, 태블릿 버전) 구현
  client/src/layout/Header.jsx
  client/src/pages/Calendar.jsx
Labels: 🎨HTML&CSS

#41 [Fe-pages] 로그인 구현중
  client/src/App.js
  client/src/assets/image/logo2.png
  client/src/layout/Nav.jsx
  client/src/pages/Login.jsx
  client/src/pages/SignUp.jsx
  client/src/style/GlobalStyle.js
Labels: 🔥Feature, 🎨HTML&CSS

#43 Feat : 게시판 리스트 조회 형식 선택 기능
  client/src/App.js
  client/src/component/Board/Dash.jsx
  client/src/component/Board/List.jsx
  client/src/component/Board/Pagination.jsx
  client/src/component/Board/boardData.js
  client/src/layout/Nav.jsx
  client/src/pages/Board.jsx
Labels: 🔥Feature

#46 Style : 스타일 가이드 수정
  client/src/App.js
  client/src/component/Board/Dash.jsx
  client/src/component/Board/List.jsx
  client/src/component/common/Button.jsx
  client/src/pages/Board.jsx
Labels: 🎨HTML&CSS

#55 [FE-component] Input 공통 컴포넌트 구현
  client/src/component/calendar/calendarAddCompo/CalendarAddHeader.jsx
  client/src/component/common/Button.jsx
  client/src/component/common/Input.jsx
  client/src/pages/Board.jsx
  client/src/pages/Board/BoardAdd.jsx
  client/src/pages/SignUp.jsx
Labels: 🔥Feature, 🎨HTML&CSS

#60 design: 캘린더 작성 페이지 css구현
  .DS_Store
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/component/calendar/calendarAddCompo/CalendarAddBody.jsx
  client/src/component/calendar/calendarAddCompo/SearchPlace.jsx
  client/src/component/common/ImageUpload.jsx
Labels: 🔥Feature, 🎨HTML&CSS

#65 feat: 커뮤니티 업로드 레이아웃
  client/src/component/Board/UploadImage.jsx
  client/src/pages/Board/Board.jsx
  client/src/pages/Board/BoardAdd.jsx
  client/src/style/GlobalStyle.js
Labels: 🔥Feature, 🎨HTML&CSS

#77 refactor:이미지 업로드 리팩토링
  client/package-lock.json
  client/package.json
  client/src/component/common/ImageUpload.jsx
  client/src/index.js
  client/src/redux/slice/imageSlice.js
  client/src/redux/store.js
Labels: 🛠️Refector

#79 feat: 회원탈퇴 모달창 구현
  client/.eslintrc.json
  client/src/App.js
  client/src/component/common/Button.jsx
  client/src/pages/User/EditUser.jsx
  client/src/pages/User/Login.jsx
  client/src/pages/User/SignUp.jsx
  client/src/pages/User/User.jsx
  client/src/pages/UserInfo.jsx
Labels: 🔥Feature, 🎨HTML&CSS

#80 design:캘린더 상세 페이지 레이아웃 구현 및 ScrollToTop적용
  client/src/App.js
  client/src/component/calendar/calendarAddComponent/CalendarAdd.jsx
  client/src/component/calendar/calendarAddComponent/SearchPlace.jsx
  client/src/component/common/ScrollToTop.jsx
  client/src/pages/calendarPage/CalendarAdd.jsx
  client/src/pages/calendarPage/CalendarDetail.jsx
Labels: 🔥Feature, 🎨HTML&CSS

#82 Fe/board
  client/src/component/Board/CommentForm.jsx
  client/src/component/Board/UploadImage.jsx
  client/src/pages/Board/Board.jsx
  client/src/pages/Board/BoardAdd.jsx
  client/src/pages/Board/BoardDetail.jsx
Labels: 🔥Feature, 🎨HTML&CSS

#83 feat : 댓글 작성 폼 레이아웃
  client/src/component/Board/CommentForm.jsx
  client/src/component/Board/UploadImage.jsx
  client/src/layout/Nav.jsx
  client/src/pages/Board/Board.jsx
  client/src/pages/Board/BoardAdd.jsx
  client/src/pages/Board/BoardDetail.jsx
Labels: 🎨HTML&CSS

#84 feat:캘린더 상세 페이지 기능 구현
  client/src/component/calendar/calendarAddComponent/CalendarAdd.jsx
  client/src/component/calendar/calendarAddComponent/SearchPlace.jsx
  client/src/component/calendar/calendarDetailComponent.jsx/CalendarDeleteModal.jsx
  client/src/pages/calendarPage/CalendarDetail.jsx
Labels: 🔥Feature

#85 fix & feat: durationTime 필드 추가 날짜 및 시간관련 타입 수정, 유효시간 세팅 로직 추가
  Sumo/src/main/java/com/codestates/exception/ExceptionCode.java
  Sumo/src/main/java/com/codestates/schedule/dto/ScheduleDto.java
  Sumo/src/main/java/com/codestates/schedule/entity/Schedule.java
  Sumo/src/main/java/com/codestates/schedule/mapper/ScheduleMapper.java
  Sumo/src/main/java/com/codestates/schedule/repository/ScheduleRepository.java
  Sumo/src/main/java/com/codestates/schedule/service/ScheduleService.java
Labels: Fix

#88 design:로딩페이지 구현
  .DS_Store
  client/src/assets/image/headalee.png
  client/src/component/calendar/CalendarComponent.jsx
  client/src/component/calendar/calendarAddComponent/SearchPlace.jsx
  client/src/component/common/Loading.jsx
Labels: 🎨HTML&CSS

#92 Fe/pagination 페이징 레이아웃
  client/src/component/Board/CommentForm.jsx
  client/src/component/Board/Pagination.jsx
  client/src/pages/Board/Board.jsx
Labels: 🔥Feature

#95 feat : 운동 기록 공유 유무에 따른 렌더링 차별화
  client/src/component/Board/BoardAdd/Record.jsx
  client/src/component/Board/BoardAdd/UploadImage.jsx
  client/src/component/Board/BoardDetail/CommentForm.jsx
  client/src/component/Board/Modal.jsx
  client/src/component/common/Button.jsx
  client/src/pages/Board/Board.jsx
  client/src/pages/Board/BoardAdd.jsx
  client/src/pages/Board/BoardDetail.jsx
  client/src/style/GlobalStyle.js
Labels: 🔥Feature, 🎨HTML&CSS

#96 S3 이미지 업로드 기능 로직 추가
  Sumo/build.gradle
  Sumo/src/main/java/com/codestates/aws/S3Config.java
  Sumo/src/main/java/com/codestates/aws/S3Uploader.java
  Sumo/src/main/java/com/codestates/exception/ExceptionCode.java
  Sumo/src/main/java/com/codestates/schedule/controller/ScheduleController.java
  Sumo/src/main/java/com/codestates/schedule/dto/ScheduleDto.java
  Sumo/src/main/java/com/codestates/schedule/mapper/ScheduleMapper.java
  Sumo/src/main/java/com/codestates/schedule/service/ScheduleService.java
  Sumo/src/main/resources/application.yml
Labels: 🔥Feature

#97 feat: 경고 메세지창 구현
  client/src/App.js
  client/src/component/calendar/CalendarAddComponent/WarningModal.jsx
  client/src/component/calendar/CalendarComponent.jsx
  client/src/component/calendar/SearchPlace.jsx
  client/src/component/calendar/TimeDropDown.jsx
  client/src/component/calendar/calendarAddComponent/CalendarAdd.jsx
  client/src/pages/Calendar/CalendarAdd.jsx
  client/src/pages/Calendar/CalendarDetail.jsx
  client/src/pages/Calendar/CalendarEdit.jsx
  client/src/style/theme.js
Labels: 🔥Feature

#102 feat : 이미지 업로드 공통 컴포넌트 사용
  client/src/component/Board/BoardAdd/UploadImage.jsx
  client/src/component/Board/Pagination.jsx
  client/src/component/Board/boardData.js
  client/src/component/common/ImageUpload.jsx
  client/src/pages/Board/Board.jsx
  client/src/pages/Board/BoardAdd.jsx
  client/src/pages/Board/BoardEdit.jsx
Labels: 🔥Feature

#105 feat: 드롭다운 수정, 캡쳐 기능 구현, landing페이지 구현 시작
  client/src/App.js
  client/src/assets/image/swimmingpool.png
  client/src/assets/image/wave.svg
  client/src/component/calendar/CalendarComponent.jsx
  client/src/component/calendar/CalendarDetailComponent/CalendarDeleteModal.jsx
  client/src/component/calendar/TimeDropDown.jsx
  client/src/component/common/ImageUpload.jsx
  client/src/layout/Nav.jsx
  client/src/pages/Calendar/Calendar.jsx
  client/src/pages/Calendar/CalendarAdd.jsx
  client/src/pages/Calendar/CalendarEdit.jsx
  client/src/pages/Landing.jsx
Labels: 🔥Feature, 🎨HTML&CSS, Fix

#108 feat: 랜딩페이지 두번째 섹션 구현 + WarningToast 파일 이동
  client/src/App.js
  client/src/assets/image/calendarEX.png
  client/src/assets/image/calendarImage.png
  client/src/assets/image/wave.png
  client/src/assets/image/wave.svg
  client/src/assets/image/wave2.png
  client/src/component/calendar/CalendarAddComponent/DonePostModal.jsx
  client/src/component/calendar/CalendarComponent.jsx
  client/src/component/calendar/CalendarDetailComponent/CalendarDeleteModal.jsx
  client/src/component/calendar/SearchPlace.jsx
  client/src/component/common/ImageUpload.jsx
  client/src/component/common/WarningToast.jsx
  client/src/layout/Header.jsx
  client/src/pages/Calendar/Calendar.jsx
  client/src/pages/Calendar/CalendarAdd.jsx
  client/src/pages/Calendar/CalendarDetail.jsx
  client/src/pages/Calendar/CalendarEdit.jsx
  client/src/pages/Landing.jsx
  client/src/pages/User/Login.jsx
Labels: 🔥Feature, 🎨HTML&CSS

#110 Fe/pagination
  client/src/App.js
  client/src/component/Board/BoardAdd/Record.jsx
  client/src/component/Board/BoardDetail/Comment.jsx
  client/src/component/Board/BoardDetail/CommentForm.jsx
  client/src/component/Board/Dash.jsx
  client/src/component/Board/List.jsx
  client/src/component/Board/Pagination.jsx
  client/src/component/common/ImageUpload.jsx
  client/src/pages/Board/Board.jsx
  client/src/pages/Board/BoardAdd.jsx
  client/src/pages/Board/BoardDetail.jsx
  client/src/pages/Board/BoardEdit.jsx
  client/src/pages/Calendar/CalendarAdd.jsx
Labels: 📬API

#118 랜딩페이지 수정
  client/src/component/Board/BoardAdd/Record.jsx
  client/src/component/Board/BoardDetail/Comment.jsx
  client/src/component/Board/Dash.jsx
  client/src/pages/Board/Board.jsx
  client/src/pages/Board/BoardDetail.jsx
  client/src/pages/Landing.jsx
Labels: 🎨HTML&CSS

#121 design: 랜딩페이지 css 수정
  client/src/component/calendar/SearchPlace.jsx
  client/src/component/calendar/TimeDropDown.jsx
  client/src/component/common/ImageUpload.jsx
  client/src/pages/Calendar/Calendar.jsx
  client/src/pages/Calendar/CalendarAdd.jsx
  client/src/pages/Calendar/CalendarDetail.jsx
  client/src/pages/Calendar/CalendarEdit.jsx
  client/src/pages/Landing.jsx
Labels: 🎨HTML&CSS

#127 Feat : 운동 기록 공유 기능
  client/src/component/Board/BoardAdd/Record.jsx
  client/src/pages/Board/BoardAdd.jsx
  client/src/pages/Board/BoardDetail.jsx
  client/src/pages/Board/BoardEdit.jsx
Labels: 🔥Feature

#132 refactor:코드 리팩토링 및 console.log제거
  client/src/component/calendar/CalendarDetailComponent/CalendarDeleteModal.jsx
  client/src/component/calendar/DonePostModal.jsx
  client/src/component/calendar/NavButton.jsx
  client/src/component/calendar/SearchPlace.jsx
  client/src/component/calendar/TimeDropDown.jsx
  client/src/component/common/ImageUpload.jsx
  client/src/component/common/Loading.jsx
  client/src/component/common/WarningToast.jsx
  client/src/pages/Calendar/Calendar.jsx
  client/src/pages/Calendar/CalendarAdd.jsx
  client/src/pages/Calendar/CalendarDetail.jsx
  client/src/pages/Calendar/CalendarEdit.jsx
Labels: 🛠️Refector

#133 feat : 데이터 없는 상태 처리
  client/src/component/Board/Dash.jsx
  client/src/pages/Board/Board.jsx
Labels: 🔥Feature

#136 fix:카카오맵api 수정
  client/public/index.html
  client/src/component/calendar/SearchPlace.jsx
Labels: Fix

#139 design:캘린더 캡쳐버튼 수정
  client/src/pages/Calendar/Calendar.jsx
Labels: 🎨HTML&CSS

#146 fix:geolocation기능 주석처리 및 지도의 기본 위치 변경
  client/src/component/calendar/SearchPlace.jsx
Labels: Fix
